### ISSUE TITLE
配置文件在哪里

### ISSUE THREAD

**Issue by cosir888** [Ftbom/mypybot#1]
看了半天运行不起来，应该差个配置文件。请问在哪里设置

**Comment by cosir888** [comment]
不知道哪里有问题。

**Comment by cosir888** [comment]
![](https://i3.wp.com/telegra.ph/file/661c519131d5209391821.jpg)
![](https://i3.wp.com/telegra.ph/file/c0b655afcb5cfe5929c42.jpg)

**Comment by cosir888** [comment]
注释掉onedrive是因为我不需要此功能

**Comment by Ftbom** [comment]
配置文件中如果没有添加onedrive会报错。我更新了代码，[现在可以不设置onedrive](https://github.com/Ftbom/mypybot/commit/ce6a38046054867a380c99a41b2253fc98fc3fec)。另外，配置文件需要自己建立，文件名是`settings.ini`

**Comment by cosir888** [comment]
> 配置文件中如果没有添加onedrive会报错。我更新了代码，[现在可以不设置onedrive](https://github.com/Ftbom/mypybot/commit/ce6a38046054867a380c99a41b2253fc98fc3fec)。另外，配置文件需要自己建立，文件名是`settings.ini`

非常感谢回复。我晚上试试。

**Comment by cosir888** [comment]
刚刚看了一下更新。清晰明了许多。大赞！

**Comment by cosir888** [comment]
刚刚看了一下更新。清晰明了许多。大赞！

**Comment by cosir888** [comment]
![](https://i1.wp.com/telegra.ph/file/db10058acee8fb7861c9d.jpg)
看样子是连不上。我终端开的有clash也连不上。哪里能改一下这个api吗？我这里有个网上找的反代
https://tg-bot.0x23.cf/
http://toso.rf.gd/

**Comment by Ftbom** [comment]
你说的反代我不太清楚。

在main.py文件开头加入以下内容可以给**Telegram Api**设置代理

```python
from telebot import apihelper
apihelper.proxy = {'http': 'http://127.0.0.1:108', 'https': 'http://127.0.0.1:108'}
```

**Comment by cosir888** [comment]
> 你说的反代我不太清楚。
> 
> 在main.py文件开头加入以下内容可以给**Telegram Api**设置代理
> 
> ```python
> from telebot import apihelper
> apihelper.proxy = {'http': 'http://127.0.0.1:108', 'https': 'http://127.0.0.1:108'}
> ```

嗯，也能解决。昨天切换了很多节点。偶尔连得上。毕竟免费节点。不稳定。嘿嘿。那个反代应该需要修改pythonbotapi库的。
