### ISSUE TITLE
通过反代官方api实现无须代理使用bot

### ISSUE THREAD

**Issue by cosir888** [Ftbom/mypybot#3]
进入python虚拟环境
cd /venv/lib/python3.10/site-packages/telebot/

 #进入pyTelegramBotAPI库修改以下文件中的https://api.telegram.org/为https://tg-bot.0x23.cf/

apihelper.py  asyncio_helper.py

可以使用vim全局替换

vim命令:
%s/api.telegram.org/tg-bot.0x23.cf/g

![](https://i1.wp.com/telegra.ph/file/9f7a389077f3b81bca455.gif)

**Comment by cosir888** [comment]
![](https://i1.wp.com/telegra.ph/file/9f7a389077f3b81bca455.gif)

**Comment by cosir888** [comment]
Using local Bot API Sever
Since version 5.0 of the Bot API, you have the possibility to run your own Local Bot API Server. pyTelegramBotAPI also supports this feature.

from telebot import apihelper

apihelper.API_URL = "http://localhost:4200/bot{0}/{1}"
Important: Like described here, you have to log out your bot from the Telegram server before switching to your local API server. in pyTelegramBotAPI use bot.log_out()

Note: 4200 is an example port


搞完一楼的笨方法，在pyTelegramBotAPI突然看到这个方案更简单有效
```python
from telebot import apihelper

apihelper.API_URL = "https://tg-bot.0x23.cf/bot{0}/{1}"
```

**Comment by Ftbom** [comment]
感谢，已添加到README
